require("muthu.init") -- Should be at the top
require("muthu.core.colorscheme")
require("muthu.core.keymaps")
require("muthu.core.options")
require("muthu.plugins.comment")
require("muthu.plugins.nvim-tree")
require("muthu.plugins.lualine")
require("muthu.plugins.telescope")
require("muthu.plugins.nvim-cmp")
require("muthu.plugins.lsp.mason")
require("muthu.plugins.lsp.lspsaga")
require("muthu.plugins.lsp.lspconfig")
require("muthu.plugins.lsp.null-ls")
require("muthu.plugins.treesitter")
require("muthu.plugins.gitsigns")
